# Generated by Django 5.2.7 on 2025-11-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetreview',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.bouquet'),
        ),
        migrations.AlterField(
            model_name='bouquetreview',
            name='text',
            field=models.TextField(verbose_name='Відгук'),
        ),
    ]
