# Generated by Django 5.2.7 on 2025-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою (Visa/MasterCard)'), ('cash', 'Наложений платіж (готівкою або терміналом)'), ('applepay', 'Apple Pay'), ('googlepay', 'Google Pay')], default='card', max_length=20),
        ),
    ]
