# Generated by Django 5.2.7 on 2025-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
