# Generated by Django 5.2.7 on 2025-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_payment_method_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(max_length=50),
        ),
    ]
