# Generated by Django 5.2.7 on 2025-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_date_alter_order_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
