# Generated by Django 5.2.7 on 2025-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою'), ('cash', 'Наложений платіж'), ('applepay', 'Apple Pay'), ('googlepay', 'Google Pay')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Стандартна | (~2 години)'), ('exact', 'В точний час | (+99 грн)'), ('express', 'Експрес | (~30 хвилин +99 грн)'), ('pickup', 'Самовивіз | (безкоштовно)')], default='standard', max_length=20),
        ),
    ]
