# Generated by Django 5.2.7 on 2025-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою'), ('cash', 'Наложений платіж'), ('applepay', 'Apple Pay'), ('googlepay', 'Google Pay')], max_length=20),
        ),
    ]
