# Generated by Django 5.2.7 on 2025-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'В корзине'), ('payment_method', 'Выбрал способ оплаты'), ('paid', 'Оплачен')], default='cart', max_length=20),
        ),
    ]
