# Generated by Django 5.2.7 on 2025-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'В корзине'), ('payment_method', 'Выбрал способ оплаты'), ('paid', 'Оплачен')], default='cart', max_length=30),
        ),
    ]
